---
title: "EDA"
output: word_document
date: "2023-10-22"
---
```{r}
housing =read.csv('data.csv')
```

```{r}
head(housing)
```

our depend variable is sale price called as price in dataset

```{r}
str(housing)
```

```{r}
# Assuming 'housing' is a data frame in R
# Select only the numerical columns
numerical_data <- housing[sapply(housing, is.numeric)]

# Create a scatterplot matrix
pairs(numerical_data,colors(distinct = TRUE))

```


```{r}
summary(housing)
```


```{r}
str(housing)
```

```{r}
# Assuming 'housing' is a data frame in R
# Get a list of all column names
column_names <- names(housing)

# Create separate histograms for each numerical variable
for (col in column_names) {
  if (is.numeric(housing[[col]])) {
    hist(housing[[col]],
         main = paste("Histogram of", col),
         xlab = col,
         ylab = "Frequency",
         col = "lightblue")
  }
}

```

histogram of our predict variable

```{r}
hist(housing$Price,col = 'yellow')
```


```{r}
boxplot(housing$Rooms,col = 'blue',main='Boxplot of Rooms ')

```


```{r}
boxplot(housing$Price,col = 'yellow',main='Boxplot of Price ')

```




```{r}
boxplot(housing$Distance,col='yellow',main='Boxplot of Distance ')

```

```{r}
boxplot(housing$Postcode,main='Boxplot of Postcode ',col = 'green')

```


```{r}
boxplot(housing$Bedroom2,main='Boxplot of Bedroom ',col = 'pink')

```


```{r}
boxplot(housing$Bathroom,main='Boxplot of bathroom  ',col = 'blue')

```



```{r}
boxplot(housing$Car,main='Boxplot of car ',col = 'red')

```


```{r}
boxplot(housing$Landsize,main='Boxplot of Landsize ',col = 'violet')

```


```{r}
boxplot(housing$BuildingArea,main='Boxplot of Building area ',col='violet')

```


```{r}
boxplot(housing$YearBuilt,col='green',main='Boxplot of Year built')

```



```{r}
boxplot(housing$Lattitude,main='Boxplot of Lattitude ',col = 'pink')

```


```{r}
boxplot(housing$Longtitude,main='Boxplot of Longtitude ',col = 'green')
```


```{r}
boxplot(housing$Propertycount,main='Boxplot of Property count ',col = 'orange')
```







